#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

setxkbmap gb &
xset -dpms s off &
setbg &
# xrandr -s 1920x1080 -r 60 &
# polybar &
setxkbmap gb &
unclutter -idle 1 -root &
xset r rate 300 50 &	# Speed xrate up
# slstatus &
dwmblocks &
xcompmgr &
emacs --fg-daemon &
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setxkbmap gb
cron -f ~/.config/cron/cron.conf &
# polybar --config=~/.config/leftwm/themes/current/polybar.config &
# $HOME/.config/leftwm/themes/current/up &
# xwallpaper --center ~/pics/ferris.png
herbe "ø Welcome to void linux"
